print('='*50)
na = input('Nome d@ alun@: ')
u1 = float(input('nota da 1º unidade: '))
u2 = float(input('nota da 2º unidade: '))
u3 = float(input('nota da 3º unidade: '))
me = (u1+u2+u3)/(3)
print('='*50)
print('A média de {} é: {:.1f}'.format(na, me))
print('='*50)
